package view.jhernandez.views;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author WIN 8
 */
public class Login extends JDialog {

    /**
     * Creates new form Login
     *
     * @param parent
     * @param modal
     */
    public Login(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JTextField();
        contraseñaTexto = new javax.swing.JPasswordField();
        panelMsj = new javax.swing.JPanel();
        advertencia = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("frame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 204, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setMaximumSize(new java.awt.Dimension(95, 45));
        jLabel1.setMinimumSize(new java.awt.Dimension(95, 45));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(95, 45));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        bienvenido.setFont(new java.awt.Font("Edwardian Script ITC", 0, 60)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(0, 204, 102));
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("Bienvenido");
        bienvenido.setMaximumSize(new java.awt.Dimension(200, 70));
        bienvenido.setMinimumSize(new java.awt.Dimension(200, 70));
        bienvenido.setOpaque(true);
        bienvenido.setPreferredSize(new java.awt.Dimension(200, 70));

        usuario.setBorder(new javax.swing.border.MatteBorder(null));
        usuario.setMaximumSize(new java.awt.Dimension(35, 15));
        usuario.setMinimumSize(new java.awt.Dimension(35, 15));
        usuario.setName(""); // NOI18N
        usuario.setOpaque(true);
        usuario.setPreferredSize(new java.awt.Dimension(35, 15));

        contraseña.setBorder(new javax.swing.border.MatteBorder(null));
        contraseña.setMaximumSize(new java.awt.Dimension(35, 15));
        contraseña.setMinimumSize(new java.awt.Dimension(35, 15));
        contraseña.setName(""); // NOI18N
        contraseña.setOpaque(true);
        contraseña.setPreferredSize(new java.awt.Dimension(35, 15));

        usuarioTexto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        contraseñaTexto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        panelMsj.setPreferredSize(new java.awt.Dimension(280, 40));
        panelMsj.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        advertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/jhernandez/icons/bullet_error.png"))); // NOI18N
        panelMsj.add(advertencia);

        mensaje.setPreferredSize(new java.awt.Dimension(250, 30));
        panelMsj.add(mensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bienvenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMsj, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(contraseñaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(usuarioTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(contraseñaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMsj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        iniciar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciar.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.add(iniciar);

        cancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelar.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.add(cancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertencia;
    private javax.swing.JLabel bienvenido;
    public javax.swing.JButton cancelar;
    public javax.swing.JLabel contraseña;
    public javax.swing.JPasswordField contraseñaTexto;
    public javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel mensaje;
    public javax.swing.JPanel panelMsj;
    public javax.swing.JLabel usuario;
    public javax.swing.JTextField usuarioTexto;
    // End of variables declaration//GEN-END:variables
}
