package view.jhernandez.views;

import java.awt.Image;
import java.util.*;
import javax.swing.*;
import org.pushingpixels.flamingo.api.ribbon.*;

/**
 *
 * @author WIN 8
 */
public class Principal extends JRibbonFrame implements Observer {

    public JRibbon ribbon;

    public JRibbonBand principal;
    public JRibbonBand insert;

    public JRibbonBand register;
    public JRibbonBand store;

    public JRibbonBand shopping;
    public JRibbonBand sale;
    public JRibbonBand history;

    public JRibbonBand themes;

    public JFlowRibbonBand font;

    public RibbonTask general;
    public RibbonTask data;
    public RibbonTask information;
    public RibbonTask lookAndFeel;

    public JLabel imagen;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    // <editor-fold defaultstate="expanded" desc="Implementación Observer">
    @Override
    public void update(Observable o, Object arg) {
        this.setVisible(true);

        if (arg != null) {
            Image usuario = (Image) arg;
            this.imagen.setIcon(new ImageIcon(usuario));
        }
    }
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
