package view.jhernandez.modals;

/**
 *
 * @author WIN 8
 */
public class Employees extends javax.swing.JPanel {

    /**
     * Creates new form Employees
     */
    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTBContenedorBotones = new javax.swing.JToolBar();
        jBAgregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jPNorth = new javax.swing.JPanel();
        jPCheckBox = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxTableEmployees = new org.jdesktop.swingx.JXTable();
        jToolBar1 = new javax.swing.JToolBar();
        cmbPageSize = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel19 = new javax.swing.JLabel();
        txtPageNumber = new javax.swing.JTextField();
        lblPageOf = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRefresh = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        lblTotalRecord = new javax.swing.JLabel();
        jPDatosEmpleado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        Izquierda = new javax.swing.JPanel();
        jLClave = new javax.swing.JLabel();
        jTFClave = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLDomicilio = new javax.swing.JLabel();
        jTFDomicilio = new javax.swing.JTextField();
        jLCelular = new javax.swing.JLabel();
        jTFCelular = new javax.swing.JTextField();
        jLCorreoE = new javax.swing.JLabel();
        jTFCorreoE = new javax.swing.JTextField();
        Centro = new javax.swing.JPanel();
        jLPuesto = new javax.swing.JLabel();
        jCBPuesto = new javax.swing.JComboBox();
        jLFechaIng = new javax.swing.JLabel();
        jXDPCalendario = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Derecha = new javax.swing.JPanel();
        Photo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTBContenedorBotones.setFloatable(false);
        jTBContenedorBotones.setRollover(true);

        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.setFocusable(false);
        jBAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTBContenedorBotones.add(jBAgregar);

        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setText("Eliminar");
        jBEliminar.setFocusable(false);
        jBEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTBContenedorBotones.add(jBEliminar);

        jBBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscar.setText("Buscar");
        jBBuscar.setFocusable(false);
        jBBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTBContenedorBotones.add(jBBuscar);

        jBModificar.setForeground(new java.awt.Color(255, 255, 255));
        jBModificar.setText("Modificar");
        jBModificar.setFocusable(false);
        jBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTBContenedorBotones.add(jBModificar);

        add(jTBContenedorBotones, java.awt.BorderLayout.PAGE_START);

        jPanelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 3, 14))); // NOI18N
        jPanelCenter.setLayout(new java.awt.BorderLayout(0, 5));

        jPNorth.setPreferredSize(new java.awt.Dimension(300, 200));
        jPNorth.setLayout(new java.awt.BorderLayout(0, 2));

        jPCheckBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jCheckBox1.setText("Mostrar todos");
        jPCheckBox.add(jCheckBox1);

        jPNorth.add(jPCheckBox, java.awt.BorderLayout.NORTH);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 200));

        jxTableEmployees.setToolTipText("");
        jxTableEmployees.setPreferredSize(new java.awt.Dimension(300, 200));
        jxTableEmployees.setShowGrid(true);
        jScrollPane2.setViewportView(jxTableEmployees);

        jPNorth.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(2, 0, 2, 0));

        cmbPageSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "50", "100" }));
        jToolBar1.add(cmbPageSize);
        jToolBar1.add(jSeparator3);

        btnFirst.setFocusable(false);
        btnFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFirst.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnFirst);

        btnPrevious.setFocusable(false);
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPrevious);
        jToolBar1.add(jSeparator4);

        jLabel19.setText("Página");
        jLabel19.setToolTipText("");
        jToolBar1.add(jLabel19);

        txtPageNumber.setEditable(false);
        txtPageNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPageNumber.setText("1");
        txtPageNumber.setMaximumSize(new java.awt.Dimension(24, 30));
        txtPageNumber.setMinimumSize(new java.awt.Dimension(24, 30));
        txtPageNumber.setPreferredSize(new java.awt.Dimension(24, 30));
        jToolBar1.add(txtPageNumber);

        lblPageOf.setText("de 0");
        jToolBar1.add(lblPageOf);
        jToolBar1.add(jSeparator5);

        btnNext.setFocusable(false);
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNext);

        btnLast.setFocusable(false);
        btnLast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLast.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLast);
        jToolBar1.add(jSeparator2);

        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRefresh);
        jToolBar1.add(jSeparator6);

        lblTotalRecord.setText("Registro Total 0 filas.");
        jToolBar1.add(lblTotalRecord);

        jPNorth.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanelCenter.add(jPNorth, java.awt.BorderLayout.NORTH);

        jPDatosEmpleado.setPreferredSize(new java.awt.Dimension(978, 450));
        jPDatosEmpleado.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(966, 316));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        Izquierda.setPreferredSize(new java.awt.Dimension(450, 300));
        Izquierda.setLayout(new java.awt.GridLayout(5, 2, 0, 40));

        jLClave.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLClave.setText("Clave:");
        jLClave.setMinimumSize(new java.awt.Dimension(15, 15));
        jLClave.setPreferredSize(new java.awt.Dimension(100, 40));
        Izquierda.add(jLClave);

        jTFClave.setPreferredSize(new java.awt.Dimension(100, 35));
        Izquierda.add(jTFClave);

        jLNombre.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLNombre.setText("Nombre:");
        jLNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        jLNombre.setPreferredSize(new java.awt.Dimension(100, 40));
        Izquierda.add(jLNombre);

        jTFNombre.setPreferredSize(new java.awt.Dimension(100, 35));
        jTFNombre.setRequestFocusEnabled(false);
        Izquierda.add(jTFNombre);

        jLDomicilio.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLDomicilio.setText("Domicilio:");
        jLDomicilio.setMinimumSize(new java.awt.Dimension(100, 40));
        jLDomicilio.setPreferredSize(new java.awt.Dimension(100, 40));
        Izquierda.add(jLDomicilio);

        jTFDomicilio.setToolTipText("");
        jTFDomicilio.setPreferredSize(new java.awt.Dimension(100, 35));
        Izquierda.add(jTFDomicilio);

        jLCelular.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLCelular.setText("Celular:");
        jLCelular.setMinimumSize(new java.awt.Dimension(100, 40));
        jLCelular.setPreferredSize(new java.awt.Dimension(100, 40));
        Izquierda.add(jLCelular);

        jTFCelular.setPreferredSize(new java.awt.Dimension(100, 35));
        Izquierda.add(jTFCelular);

        jLCorreoE.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLCorreoE.setText("Correo Electronico:");
        jLCorreoE.setMinimumSize(new java.awt.Dimension(100, 40));
        jLCorreoE.setPreferredSize(new java.awt.Dimension(110, 40));
        Izquierda.add(jLCorreoE);

        jTFCorreoE.setPreferredSize(new java.awt.Dimension(100, 35));
        Izquierda.add(jTFCorreoE);

        jPanel3.add(Izquierda);

        Centro.setPreferredSize(new java.awt.Dimension(450, 300));
        Centro.setLayout(new java.awt.GridLayout(5, 2, 0, 40));

        jLPuesto.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLPuesto.setText("Puesto:");
        jLPuesto.setMinimumSize(new java.awt.Dimension(100, 40));
        jLPuesto.setPreferredSize(new java.awt.Dimension(100, 40));
        Centro.add(jLPuesto);

        jCBPuesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBPuesto.setPreferredSize(new java.awt.Dimension(100, 35));
        Centro.add(jCBPuesto);

        jLFechaIng.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLFechaIng.setText("Fecha de Ingreso:");
        jLFechaIng.setMinimumSize(new java.awt.Dimension(100, 40));
        jLFechaIng.setPreferredSize(new java.awt.Dimension(100, 40));
        jLFechaIng.setRequestFocusEnabled(false);
        Centro.add(jLFechaIng);

        jXDPCalendario.setPreferredSize(new java.awt.Dimension(100, 35));
        Centro.add(jXDPCalendario);
        Centro.add(jLabel3);
        Centro.add(jLabel1);

        jPanel3.add(Centro);

        Derecha.setPreferredSize(new java.awt.Dimension(200, 300));
        Derecha.setLayout(new org.jdesktop.swingx.VerticalLayout());

        Photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Photo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Photo.setPreferredSize(new java.awt.Dimension(200, 200));
        Derecha.add(Photo);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Foto");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Derecha.add(jLabel2);

        jPanel3.add(Derecha);

        jScrollPane1.setViewportView(jPanel3);

        jPDatosEmpleado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPDatosEmpleado, java.awt.BorderLayout.CENTER);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Derecha;
    private javax.swing.JPanel Izquierda;
    public javax.swing.JLabel Photo;
    public javax.swing.JButton btnFirst;
    public javax.swing.JButton btnLast;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnPrevious;
    public javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbPageSize;
    public javax.swing.JButton jBAgregar;
    public javax.swing.JButton jBBuscar;
    public javax.swing.JButton jBEliminar;
    public javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBPuesto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLClave;
    private javax.swing.JLabel jLCorreoE;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLFechaIng;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPCheckBox;
    public javax.swing.JPanel jPDatosEmpleado;
    private javax.swing.JPanel jPNorth;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCenter;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jTBContenedorBotones;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFClave;
    private javax.swing.JTextField jTFCorreoE;
    private javax.swing.JTextField jTFDomicilio;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXDatePicker jXDPCalendario;
    public org.jdesktop.swingx.JXTable jxTableEmployees;
    private javax.swing.JLabel lblPageOf;
    private javax.swing.JLabel lblTotalRecord;
    private javax.swing.JTextField txtPageNumber;
    // End of variables declaration//GEN-END:variables
}
